#ifndef __mainframe__
#define __mainframe__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include
#define MAX( a, b )    ( ( a ) < ( b ) ? ( b ) : ( a ) )
#define MIN( a, b )    ( ( a ) < ( b ) ? ( a ) : ( b ) )
/** Implementing MyFrame1 */
class MainFrame : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void OnChooseLabel( wxCommandEvent& event );
		void OnQuitClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members
		//void Plot2();

		wxString label;
		wxString path1;
		wxString path20;
		wxString path21;
		wxString path22;
		wxString path3;
		wxString path4;
		wxString path5;
		wxArrayString array2, array3;

	private:
		void OnQuit( wxCommandEvent& event );
		void OnAbout( wxCommandEvent& event );


};

#endif // __mainframe__
